AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'bin/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'
Metrics/LineLength:
  Max: 100
Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
